task:
  name: FreeBSD
  freebsd_instance:
    image_family: freebsd-13-0-snap
    cpu: 4
    memory: 8G
  install_script: pkg install -y git gmake
  submodules_script: git submodule update --init --recursive --progress --jobs 4
  release_script:
    - cd Make/gcc
    - gmake release
  
